server:
  port: 8761 # port where the server will be running

eureka:
  client:
    register-with-eureka: false # So we don't register the server itself
    fetch-registry: false # Don't cache its registry information locally


